# Teclado en español
input {
    kb_layout = es
}

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun

# Autoarranque
exec-once = waybar & dunst & hyprpaper &
exec-once = systemctl --user start skwd-daemon.service

# Atajos principales
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, R, exec, $menu
bind = $mainMod, C, killactive
bind = $mainMod, M, exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating
bind = $mainMod, F, fullscreen

# Foco
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Espacios de trabajo (1-5)
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Mover ventanas
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Ratón
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Atajos para capturas de pantalla
# Print: Seleccionar área y abrir directamente en Satty para editar/guardar
bind = , Print, exec, grim -g "$(slurp)" - | satty --filename -

# Shift + Print: Seleccionar área y copiar directamente al portapapeles (sin editor)
bind = SHIFT, Print, exec, grim -g "$(slurp)" - | wl-copy

# Ctrl + Print: Capturar pantalla completa directamente al portapapeles
bind = CTRL, Print, exec, grim - | wl-copy

# Atajos para cambiar el fondo de pantalla
bind = $mainMod, W, exec, skwd-wall